services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: app
    ports: ["5432:5432"]
  cache:
    image: redis:7
    ports: ["6379:6379"]
  mqtt:
    image: eclipse-mosquitto
    ports: ["1883:1883"]
