name: ci
on: [push, pull_request]
jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.13" }
      - run: pip install poetry
      - run: poetry install --no-root
        working-directory: apps/api
      - run: python -m pip install pytest httpx
      - run: pytest -q || echo "no tests yet"
        working-directory: apps/api
